Lang = {
  -- Labs
  ['drug_lab_interact']       = '~m~[~b~E~m~]~w~ | Laboratorie',
  ['lab_owned_player']        = 'Laboratoriet er ikke tilgængeligt',
  ['drug_lab_rob']            = '~m~[~b~E~m~]~w~ | Røv Laboratorie',
  ['only_own_one_lab']        = 'Du kan kun eje ét laboratorie',
  ['press_to_buy_lab']        = '~m~[~b~E~m~]~w~ | Køb Laboratorie ~g~[%s DKK]~s~',
  ['police_raid_lab']         = '~m~[~b~E~m~]~w~ | Bryd ind i Laboratoriet',
  ['press_to_leave_lab']      = '~m~[~b~E~m~]~w~ | Gå ud af laboratoriet',
  ['not_enough_money']        = 'Du har ikke nok penge.',
  ['drug_lab_purchased']      = 'Du har købt et laboratorie og betalte %s DKK',
  ['drug_lab_sold']           = 'Du har solgt dit laboratorie og modtog %s DKK',
  ['enter_drug_lab']          = 'Gå ind i laboratoriet',
  ['sell_drug_lab']           = 'Sælg laboratoriet',
  ['not_your_drug_lab']       = 'Du kan ikke sælge et laboratorie, som du ikke ejer',
  -- Menu Text:
  ['button_yes']         	    = 'Ja',
  ['button_no']         	    = 'Nej',
  ['button_return']         	= 'Tilbage',
  -- Laptop
  ['press_to_use_laptop']     = '~m~[~b~E~m~]~w~ Bærbar',
  ['prog_bar_using_laptop']   = 'Bruger bærbar...',
  ['laptop_supplies']         = 'Forsyninger',
  ['laptop_stock']            = 'Produkter',
  ['laptop_check_supplies']   = 'Tjek forsyninger',
  ['laptop_buy_supplies']     = 'Køb forsyninger',
  ['laptop_steal_supplies']   = 'Stjæl forsyninger',
  ['laptop_check_stock']      = 'Tjek produkter',
  ['laptop_sell_stock']       = 'Sælg produkter',
  ['laptop_cur_supplies']     = 'Nuværrende forsyninger: %s',
  ['laptop_cur_stock']        = 'Nuværrende produkter: %s',
  ['laptop_pol_seize']        = 'Beslaglæg forsyninger & produkter',
  ['laptop_rob_lab']          = 'Stjæl forsyninger & produkter',
  ['supplies_level_msg']      = 'Forsyninger niveau: %s',
  ['stock_level_msg']         = 'Produkt niveau: %s',
  ['supplies_purchased']      = 'Du købte %sx antal af forsyninger og betalte %s DKK',
  ['supplies_are_full']       = 'Du kan ikke købe flere forsyninger. Nuværrende antal er maksimum.',
  ['supplies_space_full']     = 'Der er ikke nok plads til flere forsyninger. Prøv igen senere.',
  ['no_jobs_available']       = 'Ingen jobs tilgængelig i øjeblikket, prøv igen senere!',
  ['already_in_job']          = 'Du er allerede i gang med et job!',
  ['laptop_stock_level']      = 'Produkt antal: %s',
  ['laptop_sell_price']       = 'Salgspris: %s',
  ['laptop_find_buyer']       = 'Find køber til produkterne',
  ['stock_is_empty']          = 'Du har ingen produkter at sælge',
  ['no_available_buyers']     = 'Ingen buyers tilgængelig i øjeblikket, prøv igen senere!',
  ['already_selling_stock']   = 'Du er allerede i en aktiv narkohandel, færdiggør den først!',
  -- Job:
  ['job_go_to_location']      = 'Kør til ~y~%s~s~.',
  ['take_out_the_goons']      = 'Dræb ~r~fjenderne~s~.',
  ['steal_the_supplies']      = 'Stjæl ~r~køretøjet~s~ med ~b~forsyningerne~s~.',
  ['press_to_steal']          = '~m~[~b~E~m~]~w~ for at ~y~stjæle~s~ varevognen',
  ['press_to_deliver']        = '~m~[~b~E~m~]~w~ for at ~y~aflevere~s~ varevognen',
  ['progbar_stealing']        = 'Dirker låsen på køretøj...',
  ['deliver_supplies_back']   = 'Aflever ~b~forsyningerne~s~ til dit ~y~laboratorie~s~.',
  ['veh_not_matching']        = 'Dette køretøj matcher ikke arbejdskøretøjet?!',
  -- Stock Job:
  ['leave_drug_lab']          = 'Forlad ~g~laboratoriet~s~',
  ['get_in_vehicle']          = 'Sæt dig ind i ~b~lastbilen~s~',
  ['deliver_stock_drop_off']  = 'Aflever ~b~produkterne~s~ til ~y~afhentningsstedet~s~',
  ['deliver_stock']           = '~m~[~b~E~m~]~w~ for at ~y~levere~s~ produkterne',
  ['stock_sold_success']      = 'Du har solgt dine produkter og modtog %s DKK',
  -- Robbery:
  ['lab_robbery_done']        = 'Du har succesfuldt røvet forsyningerne og produkterne fra laboratoriet!',
  ['lab_robbery_in_progress'] = 'En person er igang med at hacke ind i dit laboratorie',
  ['lab_robbery_hack_fail']   = 'Du fejlede hack processen.',
  ['prog_bar_pre_hack']       = 'Forbedrer hackenhed...',
  ['prog_bar_transfer']       = 'Overfører forsyninger...',
  -- Police Seizing:
  ['lab_raid_on_going']       = 'Politiet ~r~ransag~s~ dit ~g~laboratorie~s~',
  ['prog_bar_raid_door']      = 'Åbner døren...',
  ['prog_bar_transfer2']      = 'Beslaglægger forsyninger...',


}
